# Generated by Django 4.2.28 on 2026-02-09 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of appointment')),
                ('appointment_time', models.TimeField(help_text='Start Time of appointment')),
                ('expected_duration_minutes', models.PositiveIntegerField(default=15, help_text='Expected consultation duration', validators=[django.core.validators.MinValueValidator(5)])),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=20)),
                ('reason_for_visit', models.TextField(help_text='Chief Complaints / Reason for visit', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal Notes by staff or doctor', null=True)),
                ('cancelled_reason', models.TextField(blank=True, max_length=255, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='When patient arrived', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Fee charged for this appointment', max_digits=8)),
                ('is_billed', models.BooleanField(default=False, help_text='Has invoice been generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'doctor'], name='appointment_appoint_c5b3da_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
