# Generated by Django 4.2.28 on 2026-02-09 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Medical council registration number', max_length=50, unique=True)),
                ('specialization', models.CharField(help_text='Primary specialization', max_length=100)),
                ('qualification', models.CharField(help_text='Degrees & certifications', max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('consultation_duration_minutes', models.PositiveIntegerField(default=15)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive doctors cannot receive appointments')),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['specialization', 'user__first_name'],
            },
        ),
    ]
